[package]
name = "vc4-drm-emu-shader-transpiler"
version = "0.1.0"
authors = ["Cirrus <cirrus.neptune@protonmail.com>"]
edition = "2021"

[dependencies]
num = "0.4.3"
num-derive = "0.4.2"
num-traits = "0.2.17"
naga = { version = "22.1.0", features = ["hlsl-out", "compact", "wgsl-out"] }
